namespace                  = "otus-sre-hw05"
role                       = "otus"
account                    = "otus"
pod_cpu_limit_max          = "200m"
pod_memory_limit_max       = "1024Mi"
container_cpu_limit_max    = "50m"
container_memory_limit_max = "24Mi"
pvc_storage_limit_max      = "100M"